# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-24 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Microservicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('numero_operaciones', models.IntegerField()),
                ('numero_historias', models.IntegerField()),
                ('total_puntos', models.IntegerField()),
                ('tiempo_estimado_desarrollo', models.FloatField()),
            ],
            options={
                'ordering': ['nombre'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='MicroservicioApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=500)),
                ('tiempo_estimado_desarrollo', models.FloatField()),
                ('coupling', models.FloatField()),
                ('cohesion', models.FloatField()),
                ('avg_calls', models.FloatField()),
                ('valor_GM', models.FloatField()),
            ],
            options={
                'ordering': ['nombre'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=500)),
                ('url_identificacion', models.CharField(max_length=255)),
                ('signatura', models.CharField(max_length=255)),
                ('entrada', models.CharField(max_length=255)),
                ('salida', models.CharField(max_length=255)),
                ('microservicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='microservicios.Microservicio')),
            ],
            options={
                'ordering': ['nombre'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.AddField(
            model_name='microservicio',
            name='aplicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='microservicios.MicroservicioApp'),
        ),
    ]
