# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-05 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historiasUsuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoDescomposicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=500, null=True)),
                ('observaciones', models.CharField(max_length=500, null=True)),
            ],
            options={
                'ordering': ['nombre'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Microservicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=500, null=True)),
                ('numero_operaciones', models.IntegerField(null=True)),
                ('numero_historias', models.IntegerField(null=True)),
                ('total_puntos', models.IntegerField(null=True)),
                ('tiempo_estimado_desarrollo', models.FloatField(null=True)),
                ('complejidad_cognitiva', models.FloatField(null=True)),
            ],
            options={
                'ordering': ['nombre'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Microservicio_Historia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='historiasUsuario.HistoriaUsuario')),
                ('microservicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='microservicios.Microservicio')),
            ],
            options={
                'ordering': ['microservicio'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='MicroservicioApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=500, null=True)),
                ('tiempo_estimado_desarrollo', models.FloatField(null=True)),
                ('coupling', models.FloatField(null=True)),
                ('cohesion', models.FloatField(null=True)),
                ('avg_calls', models.FloatField(null=True)),
                ('valor_GM', models.FloatField(null=True)),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='microservicios.MetodoDescomposicion')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='historiasUsuario.Proyecto')),
            ],
            options={
                'ordering': ['nombre'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=500)),
                ('url_identificacion', models.CharField(max_length=255)),
                ('signatura', models.CharField(max_length=255)),
                ('entrada', models.CharField(max_length=255)),
                ('salida', models.CharField(max_length=255)),
                ('microservicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='microservicios.Microservicio')),
            ],
            options={
                'ordering': ['nombre'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.AddField(
            model_name='microservicio',
            name='aplicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='microservicios.MicroservicioApp'),
        ),
    ]
