# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-05 03:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microservicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microservicioapp',
            name='metodo',
        ),
    ]
