# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-05 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microservicios', '0002_remove_microservicioapp_metodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='microservicioapp',
            name='metodo_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
