# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-05 04:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('historiasUsuario', '0001_initial'),
        ('microservicios', '0006_remove_microservicioapp_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='microservicioapp',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='historiasUsuario.Proyecto'),
        ),
    ]
