# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-05 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microservicios', '0007_microservicioapp_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='observaciones',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Microservicio_Historia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='historiasUsuario.HistoriaUsuario')),
                ('microservicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='microservicios.Microservicio')),
            ],
            options={
                'ordering': ['microservicio'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
    ]
