# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-20 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microservicios', '0009_auto_20200508_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='microservicio',
            name='similitud_semantica',
            field=models.FloatField(null=True),
        ),
    ]
