# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-21 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microservicios', '0010_microservicio_similitud_semantica'),
    ]

    operations = [
        migrations.AddField(
            model_name='microservicioapp',
            name='complejidad_cognitiva',
            field=models.FloatField(null=True),
        ),
    ]
