version: "2"

services:
  db-equipos:
    image: postgres:9.5
    env_file: .env    
    volumes:
      - db_data_msbacklog:/var/lib/postgresql/data/pgdata
  
  web:
    build:
      context: ./msbacklog
    env_file: .env