# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-05 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencia_Historia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='HistoriaUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=500)),
                ('prioridad', models.IntegerField()),
                ('puntos_estimados', models.IntegerField()),
                ('tiempo_estimado', models.FloatField()),
                ('escenario', models.CharField(max_length=500, null=True)),
                ('observaciones', models.CharField(max_length=500, null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['prioridad'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('sigla', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=500)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('es_publico', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sigla'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='historiasUsuario.Usuario'),
        ),
        migrations.AddField(
            model_name='historiausuario',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='historiasUsuario.Proyecto'),
        ),
        migrations.AddField(
            model_name='dependencia_historia',
            name='dependencia',
            field=models.ForeignKey(db_column='dependencia_historia', on_delete=django.db.models.deletion.PROTECT, related_name='dependencia_historia', to='historiasUsuario.HistoriaUsuario'),
        ),
        migrations.AddField(
            model_name='dependencia_historia',
            name='historia',
            field=models.ForeignKey(db_column='historia_usuario', on_delete=django.db.models.deletion.PROTECT, related_name='historia_usuario', to='historiasUsuario.HistoriaUsuario'),
        ),
    ]
