# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-27 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historiasUsuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historiausuario',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['prioridad']},
        ),
    ]
