# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-23 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiasUsuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiausuario',
            name='escenario',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
