# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-30 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historiasUsuario', '0002_auto_20200923_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='idioma',
            field=models.CharField(default='es', max_length=5, null=True),
        ),
    ]
